### ISSUE TITLE
Z-Index Map and Function

### ISSUE THREAD

**Issue by ajmueller** [connectivedx/Phoenix#141]
On recent projects, we've begun to use a z-index map and function.  Something like this for the map:

```scss
$z-index: (
	hidden: -100,
	base: 1,
	content: 10,
	nav: 50,
	modal: 100,
	tooltip: 1000,
	fancy: 8000
);
```

And this for the function:

```scss
@function z($z, $options: ()) {
	$options: map-merge((
		zMap: $z-index
	), $options);

	$zMap: map-get($options, zMap);

	// check $icon exists in $iconMap
	@if map-has-key($zMap, $z) {
		$z: map-get($zMap, $z);
	}
	@else {
		@warn "The z-index `#{$z}` is not a key in your z-index map.";
		@return null;
	}

	@return $z;
}
```
